[versions]
agp = "7.1.2"
androidX-activity = "1.4.0"
androidX-appCompat = "1.4.1"
androidX-core = "1.7.0"
androidX-fragment = "1.4.1"
androidX-lifecycle = "2.4.1"
androidX-room = "2.4.2"
coil = "1.4.0"
coroutines = "1.6.0"
kotlin = "1.6.10"
ktlint = "0.44.0"
square-okHttp = "4.9.3"
square-retrofit = "2.9.0"
square-moshi = "1.13.0"
hiddenApiRefine = "3.0.3"
protoc = "3.19.4"
grpc = "1.44.1"
appCenter = "4.4.2"
zhaobozhen = "1.0.4"
lottie = "5.0.3"
drakeet-about = "2.5.0"
drakeet-multitype = "4.3.0"
brvah = "3.0.7"
mpAndroidChart = "3.1.0"
timber = "5.0.1"
processPhoenix = "2.1.2"
once = "1.3.1"
cascade = "1.3.0"
fastScroll = "1.1.7"
appIconLoader = "1.3.1"
hiddenApiBypass = "4.3"
dexLib2 = "2.5.2"
rikkax-core = "1.3.4"
rikkax-insets = "1.2.0"
rikkax-material = "1.6.6"
rikkax-borderview = "1.1.0"
rikkax-appcompat = "1.4.1"
rikkax-layoutinflater = "1.2.0"
rikkax-recyclerview = "1.3.1"
rikkax-simplemenu-preference = "1.0.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version = "0.8.18" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.9.0" }
hiddenApiRefine = { id = "dev.rikka.tools.refine.gradle-plugin", version.ref = "hiddenApiRefine" }
ksp = { id = "com.google.devtools.ksp", version = "1.6.10-1.0.4" }

[libraries]
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinX-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

androidX-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidX-activity" }
androidX-annotation = "androidx.annotation:annotation:1.3.0"
androidX-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidX-appCompat" }
androidX-browser = "androidx.browser:browser:1.4.0"
androidX-constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.3"
androidX-core = { module = "androidx.core:core-ktx", version.ref = "androidX-core" }
androidX-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidX-fragment" }
androidX-lifecycle-liveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidX-lifecycle" }
androidX-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidX-lifecycle" }
androidX-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidX-lifecycle" }
androidX-recyclerView = "androidx.recyclerview:recyclerview:1.2.1"
androidX-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidX-room" }
androidX-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidX-room" }
androidX-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidX-room" }
androidX-viewPager2 = "androidx.viewpager2:viewpager2:1.0.0"
androidX-window = "androidx.window:window:1.0.0"
androidX-preference = "androidx.preference:preference-ktx:1.2.0"

square-leakCanary = "com.squareup.leakcanary:leakcanary-android:2.8.1"
square-moshi = { module = "com.squareup.moshi:moshi", version.ref = "square-moshi" }
square-moshi-compiler = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "square-moshi" }
square-okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "square-okHttp" }
square-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "square-retrofit" }
square-retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "square-retrofit" }

google-material = "com.google.android.material:material:1.5.0"
google-protobuf-javaLite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protoc" }
google-protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
javax-annotation = "javax.annotation:javax.annotation-api:1.3.2"
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-gen = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }
appCenter-analytics = { module = "com.microsoft.appcenter:appcenter-analytics", version.ref = "appCenter" }
appCenter-crashes = { module = "com.microsoft.appcenter:appcenter-crashes", version.ref = "appCenter" }
rikka-refine-runtime = { module = "dev.rikka.tools.refine:runtime", version.ref = "hiddenApiRefine" }
rikka-refine-annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "hiddenApiRefine" }
rikka-refine-compiler = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "hiddenApiRefine" }
zhaobozhen-me = { module = "com.github.zhaobozhen.libraries:me", version.ref = "zhaobozhen" }
zhaobozhen-utils = { module = "com.github.zhaobozhen.libraries:utils", version.ref = "zhaobozhen" }
zhaobozhen-axml = { module = "com.github.zhaobozhen.libraries:axml", version.ref = "zhaobozhen" }

lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
drakeet-about = { module = "com.drakeet.about:about", version.ref = "drakeet-about" }
drakeet-multitype = { module = "com.drakeet.multitype:multitype", version.ref = "drakeet-multitype" }
brvah = { module = "com.github.CymChad:BaseRecyclerViewAdapterHelper", version.ref = "brvah" }
mpAndroidChart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpAndroidChart" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
processPhoenix = { module = "com.jakewharton:process-phoenix", version.ref = "processPhoenix" }
once = { module = "com.jonathanfinerty.once:once", version.ref = "once" }
cascade = { module = "me.saket.cascade:cascade", version.ref = "cascade" }
fastScroll = { module = "me.zhanghai.android.fastscroll:library", version.ref = "fastScroll" }
appIconLoader = { module = "me.zhanghai.android.appiconloader:appiconloader", version.ref = "appIconLoader" }
hiddenApiBypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenApiBypass" }
dexLib2 = { module = "org.smali:dexlib2", version.ref = "dexLib2" }
rikkax-core = { module = "dev.rikka.rikkax.core:core", version.ref = "rikkax-core" }
rikkax-insets = { module = "dev.rikka.rikkax.insets:insets", version.ref = "rikkax-insets" }
rikkax-material = { module = "dev.rikka.rikkax.material:material", version.ref = "rikkax-material" }
rikkax-borderview = { module = "dev.rikka.rikkax.widget:borderview", version.ref = "rikkax-borderview" }
rikkax-appcompat = { module = "dev.rikka.rikkax.appcompat:appcompat", version.ref = "rikkax-appcompat" }
rikkax-layoutinflater = { module = "dev.rikka.rikkax.layoutinflater:layoutinflater", version.ref = "rikkax-layoutinflater" }
rikkax-recyclerview = { module = "dev.rikka.rikkax.recyclerview:recyclerview-ktx", version.ref = "rikkax-recyclerview" }
rikkax-simplemenu-preference = { module = "dev.rikka.rikkax.preference:simplemenu-preference", version.ref = "rikkax-simplemenu-preference" }

[bundles]
androidX-lifecycle = [
  "androidX-lifecycle-viewModel",
  "androidX-lifecycle-liveData",
  "androidX-lifecycle-service"
]
androidX-room = [
  "androidX-room-runtime",
  "androidX-room-ktx"
]
grpc = [
  "javax-annotation",
  "grpc-okhttp",
  "grpc-protobuf",
  "grpc-stub"
]
appCenter = [
  "appCenter-analytics",
  "appCenter-crashes"
]
zhaobozhen = [
  "zhaobozhen-me",
  "zhaobozhen-utils",
  "zhaobozhen-axml"
]
rikkax = [
  "rikkax-core",
  "rikkax-insets",
  "rikkax-material",
  "rikkax-borderview",
  "rikkax-appcompat",
  "rikkax-layoutinflater",
  "rikkax-recyclerview",
  "rikkax-simplemenu-preference"
]
